spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: products
  h2:
    console:
      enabled: true
      path: /data
      trace: true
      web-allow-others: false
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    schemas: products
    table: schema_version
    validate-on-migrate: false
